# This is the path to a folder containing the GOG db files.
db_path: /path/to/gog/dbs

# Valid values are info or debug
log_level: info
# If set to server, runs as a web service; otherwise runs as a CLI
mode: server
# The network interface to use when running in server mode
interface: 0.0.0.0
# The network port to use when running in server mode
port: 8080

# IGDB client setup
# Instructions for how to obtain a client ID & secret can be found here: https://api-docs.igdb.com/#about
igdb_client_secret: abcdefghi01234jklmno56789pqrst
igdb_client_id: 0123uvwxyz4567abcde89012fg34hi
# File to cache the IGDB setup from
cache: /path/to/cache/file

# The GOG user ID matching the result of 'select * from Users;' in the DB
users:
  12345:
    username: Bob
    db: bob-galaxy-2.0.db
  56789:
    username: Doug
    db: doug-galaxy-2.0.db
metadata:
  # Each title must match exactly as listed with --all-games; normal YAML quoting rules apply
  "7 Days to Die":
    # Each of these is optional
    max_players: no limit
    comment: I will die in less than 7 days
  "Broforce":
    max_players: 4
    comment: so many bros
  "Clue/Cluedo: The Classic Mystery Game":
    max_players: 6
# The games that will be filtered out if "Include single-player games" is unchecked
single_player:
  - "10 Second Ninja"
  - "1... 2... 3... KICK IT! (Drop That Beat Like an Ugly Baby)"
# These games will always be filtered out
hidden:
  - "ARK Editor"
  - "DARQ DLC"
  - "For Honor - Public Test"