# Path to a folder containing the GOG db files.
db_path: C:\Users\my_user\Documents\gog_db

# Valid values are info or debug
log_level: info

# If set to server, runs as a web service; otherwise runs as a CLI
mode: server

# The network interface to use when running in server mode
interface: 0.0.0.0

# The network port to use when running in server mode
port: 80

# If defined, IPs not in these CIDRs will get a 401 Unauthorized
allowed_cidrs:
  # Even single IPs must be in CIDR format
  - 127.0.0.1/32
  - 192.168.0.0/24

# IGDB client setup
# Instructions for how to obtain a client ID & secret can be found at https://api-docs.igdb.com/#about
igdb_client_secret: abcdefghi01234jklmno56789pqrst
igdb_client_id: 0123uvwxyz4567abcde89012fg34hi

# Path to a file to cache the IGDB setup from
cache: C:\Users\my_user\Documents\gog-cache.json

# The GOG user ID matching the result of 'select * from Users;' in the DB
users:
  12345:
    username: Bob
    db: bob-galaxy-2.0.db
    # Profile pic in static/ dir
    pic: bob.png
    # The CIDRs the user's request can come from (public IP for external users)
    cidrs:
      - 127.0.0.1/32
      - 192.168.1.0/24
  56789:
    username: Doug
    db: doug-galaxy-2.0.db
    pic: doug.png
    cidrs:
      - 1.2.3.4/32
metadata:
  # Each title should match exactly as listed with --all-games; normal YAML quoting rules apply
  "7 Days to Die":
    # Each of these is optional
    max_players: no limit
    comment: I will die in less than 7 days
    # The title will link to this
    url: http://some-web-site.com
  "Broforce":
    max_players: 4
    comment: so many bros
  "Clue/Cluedo: The Classic Mystery Game":
    max_players: 6
# The games that will be filtered out if "Include single-player games" is unchecked
single_player:
  - "10 Second Ninja"
  - "1... 2... 3... KICK IT! (Drop That Beat Like an Ugly Baby)"
# These games will always be filtered out
hidden:
  - "ARK Editor"
  - "DARQ DLC"
  - "For Honor - Public Test"