PLATFORMS = {
    "3do": "3DO Interactive Multiplayer",
    "3ds": "Nintendo 3DS",
    "aion": "Aion",
    "aionl": "Aion: Legions of War",
    "amazon": "Amazon",
    "amiga": "Amiga",
    "arc": "ARC",
    "atari": "Atari 2600",
    "battlenet": "Battle.net",
    "bb": "BestBuy",
    "beamdog": "Beamdog",
    "bethesda": "Bethesda.net",
    "blade": "Blade & Soul",
    "c64": "Commodore 64",
    "d2d": "Direct2Drive",
    "dc": "Dreamcast",
    "discord": "Discord",
    "dotemu": "DotEmu",
    "egg": "Newegg",
    "elites": "Elite Dangerous",
    "epic": "Epic Games Store",
    "eso": "The Elder Scrolls Online",
    "fanatical": "Fanatical",
    "ffxi": "Final Fantasy XI",
    "ffxiv": "Final Fantasy XIV",
    "fxstore": "Placeholder",
    "gamehouse": "GameHouse",
    "gamesessions": "GameSessions",
    "gameuk": "GAME UK",
    "generic": "Other",
    "gg": "GamersGate",
    "glyph": "Trion World",
    "gmg": "Green Man Gaming",
    "gog": "GOG",
    "gw": "Guild Wars",
    "gw2": "Guild Wars 2",
    "humble": "Humble Bundle",
    "indiegala": "IndieGala",
    "itch": "Itch.io",
    "jaguar": "Atari Jaguar",
    "kartridge": "Kartridge",
    "lin2": "Lineage 2",
    "minecraft": "Minecraft",
    "n64": "Nintendo 64",
    "ncube": "Nintendo GameCube",
    "nds": "Nintendo DS",
    "neo": "NeoGeo",
    "nes": "Nintendo Entertainment System",
    "ngameboy": "Game Boy",
    "nswitch": "Nintendo Switch",
    "nuuvem": "Nuuvem",
    "nwii": "Wii",
    "nwiiu": "Wii U",
    "oculus": "Oculus",
    "origin": "Origin",
    "paradox": "Paradox Plaza",
    "pathofexile": "Path of Exile",
    "pce": "PC Engine",
    "playasia": "Play-Asia",
    "playfire": "Playfire",
    "ps2": "PlayStation 2",
    "psn": "PlayStation Network",
    "psp": "PlayStation Portable",
    "psvita": "PlayStation Vita",
    "psx": "PlayStation",
    "riot": "Riot",
    "rockstar": "Rockstar Games Launcher",
    "saturn": "Sega Saturn",
    "sega32": "32X",
    "segacd": "Sega CD",
    "segag": "Sega Genesis",
    "sms": "Sega Master System",
    "snes": "Super Nintendo Entertainment System",
    "stadia": "Google Stadia",
    "star": "Star Citizen",
    "steam": "Steam",
    "test": "Test",
    "totalwar": "Total War",
    "twitch": "Twitch",
    "unknown": "Unknown",
    "uplay": "Uplay",
    "vision": "ColecoVision",
    "wargaming": "Wargaming",
    "weplay": "WePlay",
    "winstore": "Windows Store",
    "xboxog": "Xbox",
    "xboxone": "Xbox Live",
    "zx": "ZX Spectrum PC",
}